title: PDESoft 2024
preposition: at
description: >-
  Conference and workshop from 1-3 July 2024 in Cambridge, UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pdesoft.org" # the base hostname & protocol for your site, e.g. https://example.com

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.3"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    logo:
      name: Excalibur SysGenX
      img: 'excalibur-logo-1018-mini.png'
      url: 'https://excalibur-sysgenx.github.io/'
    links:
      # - name: Program
      #   relative_url: /program/
      # - name: Talks
      #   relative_url: /talks/
      # - name: Speakers
      #   relative_url: /speakers/
      - name: Location
        relative_url: /location/
        - name: Talk/poster submission
        relative_url: /submit/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: 'excalibur-logo-1018-mini.png'
    links:
      # - name: Program
      #   relative_url: /program/
      # - name: How to get there
      #   relative_url: /location/
      # - name: Tickets
      #   disabled: false
      #   absolute_url: 'https://www.cam.ac.uk'

  # Information boxes
  info_bars:
    # - title: Welcome to PDESoft 2024
    #   color: primary
    #   main_only: true
    #   text: |
    #     The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

    #     ---

    #     See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
    #  - text: Call for abstracts will open soon.
    #    color: warning
    #    pages_only: false

  # Live indications
  live:
    date: 01.07.2024
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: false
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    hidden: true
    # Talk categories
    # main_categories:
    #   - name: Solvers
    #     color: info
    #   - name: Numerical Methods
    #     color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    
    map:
      # Initial map center point
      home_coord: 52.21369, 0.1017783
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #     - Hydda.Full
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      # map_provider: "Esri.WorldTopoMap"
      default_zoom: 17

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
